### ISSUE TITLE
UI: Display the actual name of the generation preset in use instead of 'User Preset'

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#232] opened 2023-04-22 15:31 UTC
Referring to this text in the top right of chats:

![image](https://user-images.githubusercontent.com/67460148/233793215-8219e862-8c7e-4aa2-a923-5206a0363d2f.png)

**Comment by malfoyslastname** [comment] 2023-04-22 15:37
duplicate of https://github.com/luminai-companion/agn-ai/issues/120
I looked at this before and had trouble figuring out how to get the data where it needs to be.
I might take another look this weekend.

**Comment by sceuick** [comment] 2023-04-23 07:30
I've landed this in a recent commit 7a52156

**Closed as completed by sceuick** 2023-04-23 07:30 UTC
