### ISSUE TITLE
bug: agnai.chat sometimes does not load at all for certain users, for entire days

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#284] opened 2023-04-30 15:46 UTC
@sceuick investigated briefly before and could not find the cause
this is a big problem

**Comment by malfoyslastname** [comment] 2023-04-30 15:49
One person reported being able to load agnai by using a different browser. (Broken browser was Brave, working browser was Edge). I've personally experienced this problem and switching browsers didn't help (IIRC: Vivaldi, Chrome, and Firefox)

**Comment by sceuick** [comment] 2023-05-01 14:43
I can potentially put cloudflare at the edge or some other CDN.

**Comment by sceuick** [comment] 2023-05-03 13:01
Hopefully we see some improvements with the improved initial bundle size.

**Comment by sceuick** [comment] 2023-05-05 14:30
I'll close this for now as it's out of scope for the repo. I'll address this on discord if it keeps occurring. The initial bundle size has been reduced by about 85%.

**Closed as completed by sceuick** 2023-05-05 14:30 UTC

**Comment by KARISIKVideokaset** [comment] 2024-03-24 05:53
It opens the translation of the page, and you can see the original page from the translation. But when you move to another page, it becomes dark again.
![resim_2024-03-24_085438140](https://github.com/agnaistic/agnai/assets/164720110/0d32c7b1-458d-4a96-b513-d7b1675c7e50)

edit: When I delete the site's data from the browser and log in to the site again, the problem is resolved to some extent, but when I close the browser and open it again, the site goes dark.
