### ISSUE TITLE
Bug: Bot keeps saying extraordinarily

### ISSUE THREAD

**Issue by ShiftyTree19** [agnaistic/agnai#159] opened 2023-04-06 14:20 UTC
I use agnai with Horde Pygmalion 6B. Most of the time it works great but sometimes the bot seems to just freak out and start jamming in the word extraordinarily all over the place sometimes even just repeating back to back (e.g. {{char}} looks at you extraordinarily extraordinarily extraordinarily.)

**Comment by sceuick** [comment] 2023-04-06 14:29
Yeah, I encountered this quite a while ago. There was a brief period where the bug existed in the Kobold codebase and was quickly patched out. This is most likely because of a worker that serves your request that still is on this version.

**Comment by ShiftyTree19** [comment] 2023-04-06 15:32
Are there any workarounds for this right now besides just regenerating until it stops?

**Comment by sceuick** [comment] 2023-04-07 00:30
Unfortunately I don't think there is an 'exclude' workers.
There is the ability to use `trusted workers only`. I'll add this as an option. It may mean to get slower responses, but they shouldn't be using the kobold version with the bug.

**Comment by sceuick** [comment] 2023-04-07 04:20
I've added a toggle for using "trusted workers only" to the Horde AI settings in the settings page.
That's probably the best I can do right at the moment, hopefully that solves it. I've also increased the Horde timeout to 2.5 mins from 2 mins to compensate for increased wait times caused by this.

I'll close the issue for now as there isn't a lot more I can do about this.

**Closed as completed by sceuick** 2023-04-07 04:20 UTC
